[settings]
experimental = false
trusted_config_paths = ["~/github"]

[settings.ruby]
compile = false

[settings.node]
corepack = true

[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
gemini-cli = "latest"
go = "1.26.0"
java = "openjdk-25"
node = "lts"
prettier = "latest"
ruby = "3.3.11"
ruff = "latest"
sops = "latest"
terraform = "latest"
uv = "0.10.8"
