#!/usr/bin/env bash

set -e # Fail the script if any installs fail
source helpers.sh

brew_prefix=$(brew --prefix)

# Essentials
os_install wget
os_install cmake
if os_is ubuntu; then
	os_install build-essential # make and more
	os_install unzip
	os_install software-properties-common
	os_install zsh
fi
if os_is mac; then
	xcode-select --install || true
	os_install make
	os_install mono
fi

# Python package managers
pip3 install pipx   # https://pypa.github.io/pipx
pipx_install poetry # https://python-poetry.org

# Get the latest zsh and bash from homebrew (don't want to check for existing)
brew install zsh
brew install bash
# Add to the allowed shells so we can use them in chsh
grep -qxF '# Next lines generated by dotfiles/post_install.sh' /etc/shells || cat <<EOT | sudo tee -a /etc/shells
# Next lines generated by dotfiles/post_install.sh
$brew_prefix/bin/zsh
$brew_prefix/bin/bash
EOT

# Make sure we have tmux-256color support on mac
# https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95
if os_is mac; then
	curl -LO https://invisible-island.net/datafiles/current/terminfo.src.gz && gunzip terminfo.src.gz
	/usr/bin/tic -xe alacritty-direct,tmux-256color terminfo.src # Result is put in ~/.terminfo
	rm terminfo.src
fi

# Git credential manager
# https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/install.md
if have_not_installed git-credential-manager; then
	if os_is mac; then
		brew install --cask git-credential-manager
		# This install on mac annoyingly makes changes to ~/.gitconfig, so we have to undo them
		git checkout -- git/.gitconfig
	fi
	if os_is ubuntu; then
		wget "https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.3.2/gcm-linux_amd64.2.3.2.deb"
		sudo dpkg -i gcm-linux_amd64.2.3.2.deb
		rm gcm-linux_amd64.2.3.2.deb
	fi
fi

# zsh-abbr https://zsh-abbr.olets.dev/installation.html
rm -rf "$HOME/opt/zsh-abbr"
git clone https://github.com/olets/zsh-abbr --single-branch --branch main --depth 1 "$HOME/opt/zsh-abbr"

# Powerlevel10k https://github.com/romkatv/powerlevel10k#installation
rm -rf "$HOME/opt/powerlevel10k"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$HOME/opt/powerlevel10k"

# Fzf https://github.com/junegunn/fzf/
rm -rf "$HOME/opt/fzf"
git clone --depth 1 https://github.com/junegunn/fzf.git "$HOME/opt/fzf"
"$HOME/opt/fzf/install" --bin --no-update-rc

# ZSH extra completions https://github.com/zsh-users/zsh-completions
rm -rf "$HOME/opt/zsh-completions"
git clone --depth 1 https://github.com/zsh-users/zsh-completions.git "$HOME/opt/zsh-completions"

# GNU versions of important programs
if os_is mac; then
	# Don't want to check if they're already installed
	brew install gnu-sed
	brew install make
fi

# Node https://nodejs.org/en/download/package-manager
brew_install node
npm install --global npm@latest

# Rust and Cargo https://www.rust-lang.org/tools/install
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
source "$HOME/.cargo/env"

# Terminal handy tools
os_install vim
os_install tmux       # https://github.com/tmux/tmux
os_install tig        # https://github.com/jonas/tig
os_install exa        # https://github.com/ogham/exa
brew_install bat      # https://github.com/sharkdp/bat
cargo_install ripgrep # https://github.com/BurntSushi/ripgrep
os_install neofetch   # https://github.com/dylanaraps/neofetch

# Language servers
brew_install lua-language-server                # https://github.com/LuaLS/lua-language-server
os_install shellcheck                           # https://github.com/koalaman/shellcheck
npm_global_install bash-language-server         # https://github.com/bash-lsp/bash-language-server
npm_global_install vim-language-server          # https://github.com/iamcco/vim-language-server
npm_global_install typescript-language-server   # https://github.com/typescript-language-server/typescript-language-server
npm_global_install typescript                   # https://github.com/microsoft/TypeScript
npm_global_install vscode-langservers-extracted # https://github.com/hrsh7th/vscode-langservers-extracted

# Formatters and linters
os_install shfmt            # https://github.com/mvdan/sh
npm_global_install prettier # https://prettier.io/
pipx_install black          # https://black.readthedocs.io
pipx_install prospector     # https://prospector.landscape.io

# Neovim https://github.com/neovim/neovim
os_install neovim
pip3 install virtualenvwrapper # Intentionally not a --user install
# shellcheck source=/dev/null
source virtualenvwrapper.sh
npm_global_install neovim

# AWS
# <install the aws-cli>
npm_global_install aws-cdk # https://docs.aws.amazon.com/cdk/v2/guide/home.html

## Gcloud
#gcloud_sdk_url=''
#if os_is mac; then
## macOS 64-bit https://cloud.google.com/sdk/docs/install#mac
#gcloud_sdk_url="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-319.0.0-linux-x86_64.tar.gz"
#fi
#if os_is ubuntu; then
## Linux 64-bit https://cloud.google.com/sdk/docs/quickstart#linux
#gcloud_sdk_url="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-319.0.0-darwin-x86_64.tar.gz"
#fi
#if have_not_installed gcloud; then
## Download the install tar.gz
#wget $gcloud_sdk_url -O cloud-sdk.tar.gz
## Extract it to the home dir
#tar -xvf cloud-sdk.tar.gz -C ~
## Run the install script
#~/google-cloud-sdk/install.sh --usage-reporting=false --command-completion=false --path-update=false
## Remove the install tar.gz
#rm cloud-sdk.tar.gz
#fi

## Android platform tools
## https://developer.android.com/studio/releases/platform-tools
#android_sdk=""
#if os_is mac; then
#android_sdk="https://dl.google.com/android/repository/platform-tools-latest-darwin.zip"
#fi
#if os_is ubuntu; then
#android_sdk="https://dl.google.com/android/repository/platform-tools-latest-linux.zip"
#fi
#if have_not_installed adb; then
#wget $android_sdk -O android-sdk.zip
#unzip android-sdk.zip -d ~
#rm android-sdk.zip
#fi

## Java
#if os_is ubuntu; then
#if have_not_installed java; then
#os_install default-jre
#fi
#fi

## Google Cloud SQL proxy
#proxy_file_url=""
#if os_is mac; then
#proxy_file_url="https://dl.google.com/cloudsql/cloud_sql_proxy.darwin.amd64"
#fi
#if os_is ubuntu; then
#proxy_file_url="https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64"
#fi
#if have_not_installed cloud_sql_proxy; then
#curl -o /usr/local/bin/cloud_sql_proxy $proxy_file_url
#chmod +x /usr/local/bin/cloud_sql_proxy
#fi

## TODO see if we can remove duplicated code between here and bashrc
#export WORKON_HOME=~/.virtualenvs
#if os_is mac; then
#export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3.9
#source /usr/local/bin/virtualenvwrapper.sh
#fi
#if os_is ubuntu; then
#export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3.9
#source ~/.local/bin/virtualenvwrapper.sh
#fi

#
#

# NOTE: These take a long time
# Ruby and rbenv
# https://github.com/rbenv/rbenv
default_ruby_version=3.1.2
brew_install rbenv
brew_install ruby-build
eval "$(rbenv init - bash)"
rbenv install --skip-existing $default_ruby_version
rbenv global $default_ruby_version

# Gems
gem_install tmuxinator # https://github.com/tmuxinator/tmuxinator
gem_install neovim
tmuxinator doctor
# TODO: Add back in and tests
#gem_install rubocop
#gem_install neovim
#gem_install htmlbeautifier

# .NET SDK and runtime
# Ignore for now, there were some issues running it
# on the github action ubuntu:22.04 runner image
#if os_is mac; then
## Pre-requisite
## https://learn.microsoft.com/en-us/dotnet/core/install/macos#libgdiplus
#os_install mono-libgdiplus
#fi
## https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
#if have_not_installed dotnet; then
#wget https://dot.net/v1/dotnet-install.sh
#chmod +x dotnet-install.sh
#./dotnet-install.sh --channel 7.0
#rm dotnet-install.sh
#fi
