# See here for list of installed packages under 'ubuntu-24.04'

# Need to set the Github token so we can call and test gh commands
# without errors
# https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
env:
  DEBUG_INFO: true # Print out helpful info in the logs
  CI: true

name: "continuous integration"
on:
  push:
    branches: ["master"]
jobs:
  test-on-ubuntu:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0 # Deep clone
      - name: "Remove the .bash_login file"
        # Just in case it exists and our .profile doesn't get loaded
        # https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files
        run: "rm -rf ~/.bash_login"
      - name: "Install stow & adopt all the links"
        run: |
          sudo apt-get install -y stow
          ./symlink.sh --adopt
          git status
          git restore .
          git status
      - name: "Run the install script and test"
        run: "./install.sh"
  test-on-mac:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
    runs-on: "macos-15"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0 # Deep clone
      - name: "Remove the .bash_login file"
        # Just in case it exists and our .profile doesn't get loaded
        # https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files
        run: "rm -rf ~/.bash_login"
      - name: "Install stow & adopt all the links"
        run: |
          brew install stow
          ./symlink.sh --adopt
          git status
          git restore .
          git status
      - name: "Run the install script and test"
        run: "./install.sh"
